image: node:latest

# Run before each script
before_script:
  - export PEBBLE_SDK=pebble-sdk-4.5-linux64
  - export PEBBLE_PATH=daktak/pebble_uqm_watchface
  - export HOME=/builds
  - apt-get -qq update
  - apt-get -qq install -y python2.7 python2.7-dev python-virtualenv python-pip libssl-dev libffi-dev
  - npm install npm@3 -g
  - mkdir -p /builds/pebble-dev
  - mkdir -p /builds/.pebble-sdk
  - touch /builds/.pebble-sdk/ENABLE_ANALYTICS
  - if [ ! -d $HOME/pebble-dev/${PEBBLE_SDK} ]; then
  - wget https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/${PEBBLE_SDK}.tar.bz2
  - tar -jxf ${PEBBLE_SDK}.tar.bz2 -C /builds/pebble-dev/
  - cd /builds/pebble-dev/${PEBBLE_SDK}
  - sed -i '286s/.*/        return requests.get("{}{}".format(self.DOWNLOAD_SERVER, path), *args, verify=False)/' pebble-tool/pebble_tool/sdk/manager.py
  - virtualenv --no-site-packages .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - deactivate
  - pip install -U pyopenssl==0.13.1 pyasn1 ndg-httpsclient
  - fi
  - cd $HOME/${PEBBLE_PATH}

cache:
  paths:
    - /builds/pebble-dev
    - /root/.cache/pip
    - /builds/.pebble-sdk

stages:
  - build

build:
  stage: build
  script:
    - make travis_build
  artifacts:
    paths:
    - /builds/daktak/pebble_uqm_watchface/build
